version: '3.7'
services:
  db:
    image: postgres
    container_name: db 
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=easyfood
    volumes:
      - 'pgdata:/data/postgres'
  api:
    build: .
    container_name: easyfood-api 
    ports:
      - '3333:3333'
    volumes:
      - '.:/usr/app'
    links:
      - db 
    depends_on:
      - db 
volumes:
  pgdata:
    driver: local
